# Generated by Django 4.0.5 on 2022-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0003_alter_usuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dueño',
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nacimiento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
