# Generated by Django 4.0.5 on 2022-08-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSpa', '0004_remove_mascota_edad_remove_mascota_raza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dia',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
